### PEDALS ###

puts 'Creating seeds...'
# TC Electronic #
puts 'Creating pedals...'
Pedal.create(brand: "TC Electronic", model: "Cinders", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "El Cambo", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Eyemaster", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Grand Magus", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Honey Pot Fuzz", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "MojoMojo", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Rush Booster", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Spark Booster", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Spark Mini", effect: "Distortion / Gain")
Pedal.create(brand: "TC Electronic", model: "Spectra", effect: "Distortion / Gain")

Pedal.create(brand: "TC Electronic", model: "Ditto", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Ditto X4", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Dreamscape", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Drip", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "EchoBrain", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Flashback", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Flashback X4", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Hall of Fame", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Hall of Fame X4", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Nova Delay", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "Prophet", effect: "Reverb / Delay")
Pedal.create(brand: "TC Electronic", model: "SkySurfer", effect: "Reverb / Delay")

Pedal.create(brand: "TC Electronic", model: "AfterGlow", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Brainwaves", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Corona", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Helix Phaser", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Mimiq Mini", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Nether", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Nova System", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Pipeline", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Shaker Mini", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Third Dimension", effect: "Modulation")
Pedal.create(brand: "TC Electronic", model: "Viscious Vibe", effect: "Modulation")

Pedal.create(brand: "TC Electronic", model: "Crescendo", effect: "Compression / EQ")
Pedal.create(brand: "TC Electronic", model: "Forcefield", effect: "Compression / EQ")
Pedal.create(brand: "TC Electronic", model: "Hyper Gravity", effect: "Compression / EQ")
Pedal.create(brand: "TC Electronic", model: "Infinite Sustainer", effect: "Compression / EQ")
Pedal.create(brand: "TC Electronic", model: "Iron Curtain", effect: "Compression / EQ")
Pedal.create(brand: "TC Electronic", model: "Sentry", effect: "Compression / EQ")

# EXPRESSION #

Pedal.create(brand: "Dunlop", model: "CryBaby", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "CryBaby 2", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "CSTBA CryBaby", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "DimeBag Wah", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "EVH CryBaby", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "Hendrix CryBaby", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "Slash CryBaby", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "Tom Morello Wah", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "Volume", effect: "Expression")
Pedal.create(brand: "Dunlop", model: "Volume X8", effect: "Expression")

# MXR #

Pedal.create(brand: "MXR", model: "Dyna Comp", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Super Comp", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Dyna Comp Mini", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Studio Compressor", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Noise Clamp", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Smart Gate", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Six Band EQ", effect: "Compression / EQ")
Pedal.create(brand: "MXR", model: "Ten Band EQ", effect: "Compression / EQ")

Pedal.create(brand: "MXR", model: "Carbon Copy", effect: "Reverb / Delay")
Pedal.create(brand: "MXR", model: "Carbon Copy Deluxe", effect: "Reverb / Delay")
Pedal.create(brand: "MXR", model: "Carbon Copy Mini", effect: "Reverb / Delay")
Pedal.create(brand: "MXR", model: "M300 Digital Reverb", effect: "Reverb / Delay")

Pedal.create(brand: "MXR", model: "Analog Chorus", effect: "Modulation")
Pedal.create(brand: "MXR", model: "EVH Flanger", effect: "Modulation")
Pedal.create(brand: "MXR", model: "EVH 5150 Chorus", effect: "Modulation")
Pedal.create(brand: "MXR", model: "EVH Phase 90", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Micro Chorus", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Micro Flanger", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Mini Phase 95", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Phase 90", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Phase 100", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Stereo Chorus", effect: "Modulation")
Pedal.create(brand: "MXR", model: "Uni-Vibe", effect: "Modulation")

Pedal.create(brand: "MXR", model: "Blue Box", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Booster Mini", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Classic 108 Fuzz", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Custom Badass '78", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Distortion +", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Distortion III", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "EVH 5150 Overdrive", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Fullbore Metal", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "GT-OD", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Micro Amp", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Micro Amp +", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Custom Badass Modified OD", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Octavio", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Power 50", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Raw Dawg", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Octave Fuzz", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Sub Machine", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Sugar Drive", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Super Badass", effect: "Distortion / Gain")
Pedal.create(brand: "MXR", model: "Timmy", effect: "Distortion / Gain")

# BOSS #

Pedal.create(brand: "Boss", model: "Compressor CP-1X", effect: "Compression / EQ")
Pedal.create(brand: "Boss", model: "Equalizer GE-7", effect: "Compression / EQ")
Pedal.create(brand: "Boss", model: "Noise Suppressor NS-2", effect: "Compression / EQ")

Pedal.create(brand: "Boss", model: "Digital Delay DD-8", effect: "Reverb / Delay")
Pedal.create(brand: "Boss", model: "Reverb RV-6", effect: "Reverb / Delay")
Pedal.create(brand: "Boss", model: "Reverb RV-500", effect: "Reverb / Delay")

Pedal.create(brand: "Boss", model: "Chorus Ensemble CE-5", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Flanger BF-3", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Loop Station RC-500", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Modulation MD-200", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Octave OC-5", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Phase Shifter PH-3", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Super Chorus CH-1", effect: "Modulation")
Pedal.create(brand: "Boss", model: "Tremolo TR-2", effect: "Modulation")

Pedal.create(brand: "Boss", model: "Blues Driver BD-2", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Distortion DS-1", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Heavy Metal HM-2w", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Hyper Drive OD-200", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Mega Distortion MD-2", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Metal Zone MT-2", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Overdrive OD-3", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Super Overdrive SD-1", effect: "Distortion / Gain")
Pedal.create(brand: "Boss", model: "Fuzz FZ-1w", effect: "Distortion / Gain")


# Walrus #

Pedal.create(brand: "Walrus Audio", model: "Badwater", effect: "Compression / EQ")
Pedal.create(brand: "Walrus Audio", model: "Deep Six", effect: "Compression / EQ")
Pedal.create(brand: "Walrus Audio", model: "EB-10", effect: "Compression / EQ")
Pedal.create(brand: "Walrus Audio", model: "Emissary", effect: "Compression / EQ")

Pedal.create(brand: "Walrus Audio", model: "385", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Ages", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Eras", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Iron Horse", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Jupiter", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Kangra", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Voyager", effect: "Distortion / Gain")
Pedal.create(brand: "Walrus Audio", model: "Warhorn", effect: "Distortion / Gain")

Pedal.create(brand: "Walrus Audio", model: "Warhorn", effect: "Modulation")
Pedal.create(brand: "Walrus Audio", model: "Warhorn", effect: "Modulation")
Pedal.create(brand: "Walrus Audio", model: "Warhorn", effect: "Modulation")

Pedal.create(brand: "Walrus Audio", model: "ARP-87", effect: "Reverb / Delay")
Pedal.create(brand: "Walrus Audio", model: "Descent", effect: "Reverb / Delay")
Pedal.create(brand: "Walrus Audio", model: "Fathom", effect: "Reverb / Delay")
Pedal.create(brand: "Walrus Audio", model: "Lore", effect: "Reverb / Delay")
Pedal.create(brand: "Walrus Audio", model: "R1", effect: "Reverb / Delay")
Pedal.create(brand: "Walrus Audio", model: "Slo", effect: "Reverb / Delay")
Pedal.create(brand: "Walrus Audio", model: "Slotva", effect: "Reverb / Delay")

puts 'Seeding done...'